# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

<p>
The major difference between a vector and a matrix is their dimensionality. A vector is a one-dimensional array that represents a quantity with direction and magnitude, typically used to store a list of values. In contrast, a matrix is a two-dimensional array that organizes data in rows and columns, and is commonly used to represent linear transformations or systems of equations. Vectors can be seen as a special case of matrices with either one row or one column.
</p>

**2. How to import `NumPy` library?** 

In [1]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [2]:
list_1 = [1,2,3,4,5]

In [58]:
arr = np.array(list_1)
print(f"{repr(arr)}, {type(arr)})")

array([1, 2, 3, 4, 5]), <class 'numpy.ndarray'>)


(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [10]:
arr2 = np.arange(0, 6)
print(repr(arr2))


array([0, 1, 2, 3, 4, 5])


array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [11]:
arr3 = np.zeros(5)
print(repr(arr3))

array([0., 0., 0., 0., 0.])


array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [13]:
arr4 = np.zeros((3,4))
print(repr(arr4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [14]:
arr5 = np.ones(5)
print(arr5)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [18]:
arr6 = np.full(5, 10)
print(repr(arr6)) 

array([10, 10, 10, 10, 10])


array([10, 10, 10, 10, 10])


**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [19]:
arr7 = np.arange(50, 100, 2) 
print(repr(arr7))

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])


array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [31]:
arr8 = np.linspace(0, 1, 10)
print((arr8, arr8[1] - arr8[0]))

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]), 0.1111111111111111)


(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [32]:
arr9 = np.arange(0, 25)
print(repr(arr9)) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])


In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr10 = np.reshape(arr9, (5,5))
print(repr(arr10)) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr9.shape = (5,5)
print(repr(arr9))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [42]:
arr11 = np.arange(0.1, 2.6, 0.1).reshape(5, 5) 
print(repr(arr11))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [47]:
arr12 = np.linspace(0, 24, 25, dtype= int).reshape(5, 5)
print(repr(arr12)) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

<p>
<li> arange() takes a step size as an argument.</li><br>
<li> linspace(), on the other hand, takes the desired number of elements (num) to be generated.</li><br>
<li> arange() excludes the stop value</li><br>
<li> linspace() includes both the start and the stop values by default</li>

**15. How to generate a single random integer number using NumPy built-in function?**

In [50]:
random_num = np.random.randint(0, 10)
print(random_num)

2


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [51]:
matrix = np.random.rand(7, 5)
print(matrix)

[[0.96640402 0.83407528 0.95271653 0.02378371 0.94660834]
 [0.48317945 0.69351609 0.90808803 0.43354012 0.81179444]
 [0.90222758 0.97692143 0.56695803 0.35812039 0.80402352]
 [0.92261474 0.84563167 0.1613625  0.55713417 0.77212026]
 [0.79442944 0.27647992 0.06452924 0.66561455 0.48276418]
 [0.10808866 0.49187575 0.66610867 0.81420884 0.44215588]
 [0.54412773 0.90085406 0.89059859 0.70779058 0.89525305]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [53]:
identity_matrix = np.identity(5) * 5
print(repr(identity_matrix)) 

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])


array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])


### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 